## Общие настройки для ВСЕХ сервисов
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*" # Включаем все актуаторы для всех сервисов

integration:
  services:
    accounting:
      url: ${ACCOUNTING_SERVICE_URL:http://ACCOUNTING-SERVICE}
    security:
      url: ${SECURITY_SERVICE_URL:http://SECURITY-SERVICE}
    profiler:
      url: ${PROFILER_SERVICE_URL:http://PROFILER-SERVICE}